model:
  model_builder: TransformerClassifier
  train:
    learning_rate: 1.0e-6
    warmup_steps: 4000
    max_epoch: 100
    batch_size: 32
    validation_freq: 2
    model_save_freq: 20
dataset:
  seq_pad_length: 30
  train_dataset_builder: ChineseTitleDataset
  test_dataset_builder: ChineseTitleDataset