model:
  model_builder: TransformerClassifier
  train:
    learning_rate: 5.0e-6
    warmup_steps: 4000
    max_epoch: 30
    batch_size: 32
    model_save_freq: 10
dataset:
  seq_pad_length: 30
  train_dataset_builder: ChineseTitleDataset
  test_dataset_builder: ChineseTitleDataset